[project]
name = "django-birthday20"
version = "0.1.0"
description = "20th birthday celebration website for Django project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hugo==0.147.9",
]
