name: Create Event
description: Submit a new event to be added to the community calendar.
title: "[Event] "
labels: ["event"]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Title of the event
      placeholder: e.g. Django (birth)day Mombasa
    validations:
      required: true

  - type: input
    id: event_host
    attributes:
      label: Host group
      placeholder: your community's name or name(s) of organizers
    validations:
      required: true

  - type: dropdown
    id: event_type
    attributes:
      label: Event type
      options:
        - in_person
        - online
        - hybrid
        - radio
    validations:
      required: true

  - type: dropdown
    id: event_category
    attributes:
      label: Event category
      options:
        - meetup
        - conference
        - other
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Event date
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: local_time
    attributes:
      label: Local time
      placeholder: e.g. 18:30 ("TBD" if unknown or leave empty if full-day)

  - type: input
    id: timezone
    attributes:
      label: Timezone (UTC offset)
      placeholder: e.g. +03:00
    validations:
      required: true

  - type: input
    id: short_description
    attributes:
      label: Short description
      placeholder: One-liner description of the event
    validations:
      required: true

  - type: textarea
    id: long_description
    attributes:
      label: Long description
      description: Markdown supported.
      placeholder: Detailed event info
    validations:
      required: true

  - type: textarea
    id: how_to_attend
    attributes:
      label: How to attend
      description: Brief instructions on how to join or participate
      placeholder: e.g. "Join via Zoom", or "Come with your laptop"
    validations:
      required: true

  - type: input
    id: rsvp
    attributes:
      label: RSVP Instructions or URL
      placeholder: e.g. https://2025.djangocon.africa/

  - type: input
    id: event_language
    attributes:
      label: Event language
      placeholder: e.g. Swahili
    validations:
      required: true

  - type: input
    id: venue_name
    attributes:
      label: Venue name
      placeholder: Only for meetups/conferences

  - type: input
    id: venue_address
    attributes:
      label: Venue address
      placeholder: Only for meetups/conferences

  - type: input
    id: latitude
    attributes:
      label: Event latitude (optional)
      placeholder: e.g. -4.0435

  - type: input
    id: longitude
    attributes:
      label: Event longitude (optional)
      placeholder: e.g. 39.6682

  - type: textarea
    id: social_media
    attributes:
      label: Social media accounts (optional)
      placeholder: One URL per line

  - type: checkboxes
    id: coc_agreement
    attributes:
      label: Code of Conduct
      description: The event follows the [Django Code of Conduct](https://www.djangoproject.com/conduct/) or other similar Code of Conduct.
      options:
        - label: Yes, the Django Code of Conduct or other adequate Code of Conduct is applied.
          required: true
